<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>cmdbwebhooks2kafka</AssemblyName>
    <RootNamespace>CmdbWebhooks2Kafka</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../shared/Cmdb2MonitoringServiceSuppression.Shared.csproj" />
  </ItemGroup>

</Project>
