<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Cmdb2MonitoringServiceSuppression.Shared</AssemblyName>
    <RootNamespace>Cmdb2MonitoringServiceSuppression.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Confluent.Kafka" Version="2.8.0" />
  </ItemGroup>

</Project>
