<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>zabbixconfig2api</AssemblyName>
    <RootNamespace>ZabbixConfig2Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <ProjectReference Include="../shared/Cmdb2MonitoringServiceSuppression.Shared.csproj" />
  </ItemGroup>

</Project>
